### ISSUE TITLE
No cloud with openni.launch

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot#10]
No cloud being viewed when running openni.launch

**Comment by stonier** [comment]
openni_launch:
- if depth_registration is true, we can see on /camera/depth_registered/image_raw
  *\* but no /camera/depth/points
- if depth_registration is false, the situation is reversed

Note that the openni_camera nodelet is using depth_registration true, and /camera/depth/points is working.

Wtf is depth_registration? :P

**Comment by tfoote** [comment]
Depth registration turns on registration of the color image with the depth
image.  Otherwise you get a color image and the depth image, from their
own coordinate frame.  I think you should see the points coming out at
/camera/color/points with registration on.

On Thu, Sep 27, 2012 at 4:58 PM, Daniel Stonier notifications@github.comwrote:

> openni_launch:
> - if depth_registration is true, we can see on
>   /camera/depth_registered/image_raw *\* but no /camera/depth/points
> - if depth_registration is false, the situation is reversed
> 
> Note that the openni_camera nodelet is using depth_registration true, and
> /camera/depth/points is working.
> 
> Wtf is depth_registration? :P
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/turtlebot/turtlebot/issues/10#issuecomment-8959131.

## 

Tully Foote
tfoote@willowgarage.com
(650) 475-2827

**Comment by LucidOne** [comment]
I believe depth_registration is to enable/disable hardware registration.
AFAIK, the Kinect does not support hardware depth registration, but the
Xtion and the PrimeSensor do.

**Comment by stonier** [comment]
Ok, I'm crystal now. If you want to do less processing and just work on depth clouds, you turn it off. Otherwise flag it so that openni knows it has to apply the transform.

Interesting about the xtion.
