### ISSUE TITLE
Battery info not working on reference laptop?

### ISSUE THREAD

**Issue by corot** [turtlebot/turtlebot#102]
Need to dig more on this, but looks like the battery reader script needs a review. On ASUS laptops I have noticed that:
- battery info is on /sys/class/power_supply/BAT0, and not on default /proc/acpi/battery/BAT0
- charging symbol doesn't appear in the dashboard

Am I missing something? Is current configuration a legacy of the previous reference laptop?

**Comment by corot** [comment]
There was a similar problem 7 months ago, fixed on https://github.com/turtlebot/turtlebot/pull/61, but apparently strikes back

**Comment by corot** [comment]
Interestingly enough, our Chopin laptop still works as expected, and battery info is on /proc/acpi/battery/BAT0. Something changed in the configuration of the other laptops.

**Comment by rk4an** [comment]
We just made a clean install of **Ubuntu 12.04.3 LTS** and the default kernel are **3.8.0-31-generic** instead of previous **3.2.0-53-generic-pae** (default netbook ASUS 1025C)

So file are moved from _/proc/acpi/battery/BAT0_ to _/sys/class/power_supply/BAT0_

But  the new **laptop_hardware.py** file doesn't work because some files was renamed:
- no **energy_now** file but a **charge_now**
- no **energy_full_design** file but a **charge_full_design**
- no **power_now** file

**Comment by corot** [comment]
Ok, finally I took some time to dig on this:
- The pull request doesn't affect 3.2.\* and below kernels, so I merged it
- The problem stated in the issue doesn't get affected neither; the problem is in the way we process the information on BAT0 files (I'll fix all this tomorrow)
  - Values must be divided by 10e6
  - Current doesn't get possitive when charging, so the charging symbol never appears 
  - _Design Capacity_ is lower than _Capacity_; I suppose this is wrong
- /proc/acpi/battery/BAT0 has being deprecated for ages, and definitively removed in most systems (more details [here](http://www.mersenneforum.org/showthread.php?t=16779&page=4%20)), so I'll change the default path to /sys/class/power_supply/BAT0
