### ISSUE TITLE
Changing Serial Port

### ISSUE THREAD

**Issue by hofes** [turtlebot/turtlebot#111]
Isn't there a better way of changing the serial port (from ttyUSB0 to ttyS0) than changing the launch/includes/mobile_base.launch.xml.
Doing so always makes it necessary to change the launch file after every update of the turtlebot stack or to copy the turtlebot_bringup to a different (e,g. myrobot_bringup) package. Couldn't a environment variable be a better solution than hardcoding the port in the launch file.

**Comment by tfoote** [comment]
The parameter is set for the default configuration of the TurtleBot.  The clean way to do this is to use launch arguments with a default value. Which get passed down to the lower level launch files.  In practice very few people use a different port. which is why we have not taken the time to make it parameterizable. If you'd like to do that a patch would be appreciated.  However I think it will be easier work around for you to simply update your system to symlink ttyS0 to ttyUSB0.

**Comment by bit-pirate** [comment]
I don't know your exact use case, but for Kobuki we added extra information to the FTDI chip, what let's automatically  create the right symlink using a UDEV rule.

I assume you are using the Create. You might be able to create such a script for your specific Create as well (if you do, please share it here with the other create users).

**Comment by mayrjohannes** [comment]
In this particular case a roomba is used and we are directly connected to a serial port of the on board mainboard. So there is no USB Serial converter in between. I think just creating a symlink can cause troubles if using an additional USB Serial converter. The best solution would be to add the parameter as proposed by tfoote as an launch argument. We will change this and supply a patch the next days.
What is the correct way to do so? A pull request on github?

**Comment by tfoote** [comment]
Yeah, A pull request on github will get this taken care of the quickest.

**Comment by jihoonl** [comment]
#112 fixed.
