### ISSUE TITLE
Separate or make option use of robots-in-concert framework in minimal.launch in Indigo

### ISSUE THREAD

**Issue by mirzashah** [turtlebot/turtlebot#151]
@stonier Though the concept of robots-in-concert app manager stuff seems useful and makes sense in the big picture...would it be possible to make it optional? It seems counter-intuitive for minimal.launch to do more than bring up the base driver, 3d sensor, robot state publisher, and robot pose ekf. It can also mess with folks using their own multi-master implementation. 

I would suggest something like minimal_with_rocon.launch or minimal_without_rocon.launch.

**Comment by stonier** [comment]
We're in the middle of experimenting with turtlebot interactions and haven't finalised exactly how we want to introduce these over the next distro or two (very happy to chat about this). The app manager is not new, but I guess we're thinking about integrating it more fundamentally. It is however, merely a bringup/roslaunch manager. All it does is make it easy to expose and select which launcher you want to start instead of having to 1) go to the wiki, 2) find the right part of the documentation 3) ssh in 4) roslaunch from the command line. Or even worse...spend hours poking around the launchers in the various packages to see what works. You can of course, still launch things independently of the app manager if you want.

The other thing we're experimenting with is osrf's new capability server to simplify writing apps (launchers).  Right now though, there's still a few outstanding issues to be sorted out so the decision is still pending. The app manager's job will be to facilitate this so writing a new app becomes very simple. e.g. you shouldn't have to think or be exposed to every detail in the navigation stack to just 'get navigation'. Anyway, this is a ways off and we'll definitely still support the old style through indigo - note that the app manager while idle doesn't do anything significant so it shouldn't get in the way for most people. 

If you're dead set on customising it, it would be easy just to replicate minimal.launch (it is only a few lines). My preference is for just having two launchers for the turtlebot - one standalone and one multimaster. More than that is more maintenance for us and extra confusion for the new user.

Also, we've never had the 3dsensor as part of minimal that I can remember.

Note that none of the above is about multi-master and consequently `minimal.launch` doesn't do any multi-master. We also agree that minimal shouldn't confuse the user with use case settings that are probably not going to be used in 90% of instances. That is why there is a second `concert_client.launch` launcher.

**Comment by mirzashah** [comment]
@stonier Ah I get it...my mistake on the 3d sensor being in minimal. Also I was mistaken about a multimaster being brought up. My frustration came from building from source as packages haven't been released yet and finding about a dozen additional packages were needed just to bring up the base. A lot of the app manager nodes were producing errors/crashing for me --  took me a while to get through it. If they were already debs, I probably wouldn't have even noticed it. So I'll just make my own launch file until you guys release the debs.

The capabilities/app manager/robots in concert stuff sounds fantastic -- if Yujin and OSRF are behind it I'm sure it'll come out great so I support it :) 

I was also surprised by the robots in concert push given that OSRF + the community is moving along on ROS 2...seemed like there was a lot of overlap particularly with things like automatic node discovery.

**Comment by stonier** [comment]
If you come across any bugs in the install process, be sure to post them!

Think of ros 2.0 as the underlying technology, rocon is/will be one kind of glue on top. Unfortunately it's taken a bit longer for ros 2.0 to come along (and will be a long while yet) so we needed to move on some things and are using basic ros comms and zeroconf as 'stubs' till the time comes when we can slot in ros 2.0 components.

At least...that's the **master** plan :neckbeard:

**Comment by jihoonl** [comment]
:neckbeard:

**Comment by mirzashah** [comment]
Oh that "master pun" + neckbeard made my night :) 

Ah I was suspecting you guys were using ros 1.0 + zeroconf as a stopgap measure for ROS 2. Totally makes sense. Ok, good to know they're complimentary rather than competitors. It sounds useful and a  strong progression on the status quo. It actually lines up nicely with an upcoming need we have, so I'll  play with it when I get the chance and attempt to adopt it.

Oh and just to be clear, the errors I was getting were due to an incomplete installation. I kept overlaying packages one by one based on the errors I was getting...by the 4th one I went bananas and hunted down the .rosinstall file. After adding all the additional packages, it was working. Then I reverted my workspace to just kobuki/core/msgs to simplify the compile and made a new launch file based on hydro as you suggested.
