### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by mkdmkk** [turtlebot/turtlebot#168]
For installing Turtlebot, I followed the tutorial, http://wiki.ros.org/turtlebot/Tutorials/indigo/Installation.

When I try to run the command, rosdep install --from-paths src -i -y, the following error message is printed.

> wstool init -j5 src https://raw.github.com/robotics-in-concert/rocon/indigo/rocon.rosinstall
> source /opt/ros/indigo/setup.bash
> rosdep install --from-paths src -i -y
> ERROR: the following packages/stacks could not have their rosdep keys resolved
> to system dependencies:
> rocon_qt_library: Cannot locate rosdep definition for [world_canvas_msgs]

**Comment by jihoonl** [comment]
It was because of missing dependency on [world canvas framework](https://github.com/corot/world_canvas). It is not patched with the following commit https://github.com/robotics-in-concert/rocon/commit/d707509d16feda88d5ac1f9e1a9e77665ba07c71

It should work for now. Please re-open it if it still causes any other problem.

**Comment by bit-pirate** [comment]
> It is not patched with the following commit

Probably should say: It is _now_ patched with the following commit. 

:smile:
