### ISSUE TITLE
turtlebot_joy.cpp is generic enough

### ISSUE THREAD

**Issue by 130s** [turtlebot/turtlebot#206]
(With a risk of hitting FAQ) For example I can use the node in my own package without specifying anything specific to Turtlebot ([see this](https://github.com/tork-a/spur/pull/15/files)). 
How about moving it to somewhere common, eg. https://github.com/ros-drivers/joystick_drivers?

**Comment by mikeferguson** [comment]
If it were going to be merged with something, it should be merged with https://github.com/ros-teleop/teleop_twist_joy

**Comment by mikeferguson** [comment]
Also, I think teleop_twist_joy is mainly missing the mux support (as far as being a drop in replacement)

**Comment by mmwise** [comment]
I think I am torn by this largely because TurtleBot is meant to be instructional and stable. 

In terms of instructional all the code is in one place for people to look at and understand what is going on and has several options configured specifically for te TurtleBot. However it may model ROS inproperly by making yet another teleop package... 

In terms of stability the TurtleBot tutorials all depend on these launch files etc and would then need to be maintained/changed to reflect the locations of the new launch files. Along with updating other higher level launch files.

**Comment by tfoote** [comment]
I think it's fine to keep them separate for now. Migrating it will be a large effort and there's a lot of references etc to the current state which is not broken and does not have a pressing need to change in itself.

If you want specific functionality provided by turtlebot_joy I'd say go ahead and use it, or better submit a pull-request to add that capability to teleop_twist_joy. I agree that creating yet another teleop package does not make sense.

If teleop_twist_joy reaches the superset of turtlebot_joy we can choose to switch the implementation, or update the launch files in turtlebot packages.

**Comment by 130s** [comment]
All comments make sense to me. I switched my application to https://github.com/ros-teleop/teleop_twist_joy as well. Thanks!
