### ISSUE TITLE
Where can I find the costmap files, base global planner yaml file?

### ISSUE THREAD

**Issue by RajathSwaroop** [turtlebot/turtlebot#266]
Hi, I have been working with turtlebot ROS package for quite some time now and I wish to change the minimum command velocity speed and some other settings related to the command velocity limits. I need to perform these changes in the base global planner yaml file which I am not able to locate for the turtlebot. Can any one post if they have already explored this area.

I wish to provide my turtlebot reverse commands (go back command) when the goal I set is behind the robot with orientation difference between the robot and goal is over 120  degree. Is this possible with the help of negative command velocity. If I set minimum command velocity negative for the turtlebot will it send negative command velocity for goals behind the robot?

**Comment by tfoote** [comment]
Please ask questions on http://answers.ros.org according to our support policy: http://wiki.ros.org/Support We try to keep the issue tracker reserved for bugs and feature developments.

Please tag your question appropriately. And also I'd suggest breaking this into two separate questions since there's two topics which can be addressed separately.
