### ISSUE TITLE
Double Pendulum Reset

### ISSUE THREAD

**Issue by Coder9523** [turtlebot/turtlebot#267]
I am facing a problem concerning the synchronization between gazebo clock and tf time stamp once the service "Reset Simulation" is called.
i am currently working on the double pendulum simulation and noticed that there's an issue with the " Reset Simulation", for it doesn't reset the time stamp of the tf topic.
This causes a desynchronisation between the Gazebo "clock" which resettled to zero after the "Reset Simulation" whereas the tf time stamp remained equal to the last timestep before the reset. 

However, this issue is solved in TurtleBot.
![selection_012](https://user-images.githubusercontent.com/39518142/40493749-019d1f68-5f7c-11e8-8c37-a01961baca38.png)
![selection_013](https://user-images.githubusercontent.com/39518142/40493751-01c8e896-5f7c-11e8-812e-c38e369a1480.png)
![selection_015](https://user-images.githubusercontent.com/39518142/40493752-01f281e2-5f7c-11e8-8914-16f38e05a446.png)

Can anyone help me solve this matter ?

**Comment by tfoote** [comment]
Since this isn't a turtlebot issue this is not the right place to report it. Please take this up on the appropriate tracker for the double pendulum. I suspect that it's missing something to do with the publication of the simulated time. You'll also want to clarify what you're getting and what you expect more clearly. "the tf time stamp remained equal to the last timestep before the reset" it not clear what stamp on what data, published by what process you're talking about. Enough information to completely reproduce your problem is important for us to be able to help you. Include all the setup and commands that you're running and then the outputs. And please don't screenshot terminal outputs. Copy and paste them and quote them so they're searchable and copyable for being able to be reproduced.
