### ISSUE TITLE
Find a solution for confusing odom/odom_combined tf naming issue

### ISSUE THREAD

**Issue by bit-pirate** [turtlebot/turtlebot#58]
robot_pose_ekf is by default publishing the result of the fusion of odometry and gyro data as odom_combined. However, currently we call this frame just odom.

There might be reasons for using odom - probably historical ones.
Let's discuss this and make a documented decision.

**Comment by rgariepy** [comment]
Technically, robot_pose_ekf is the one that's wrong:
http://ros.org/reps/rep-0105

**Comment by bit-pirate** [comment]
Quick reply! :-)
Daniel and I don't like the convention chosen in the REP (Jorge however is in favour of that).
Do you know, if this topic has been discussed thoroughly? If yes, is this discussion documented somewhere?
We would like to know, why it has been decided like this. For example, naming it odom_combined give the user a hint that this is not just normal (wheel) odometry data.

**Comment by rgariepy** [comment]
Looks like it's capturing what were internal WG defacto standards:
https://code.ros.org/gf/project/ros/mailman/?_forum_action=ForumMessageBrowse&thread_id=42397&action=ListThreads&mailman_id=8

There will always be more sensors which one can add and are still
considered "odometry" (ex. scan matching for visual odometry) - I like
"odom" as "what you can get just based on the base platform alone".

-R

**Comment by chadrockey** [comment]
Yes, robot_pose_ekf is the one to blame here.  Putting aside the various issues that robot_pose_ekf has, this issue is pretty easy to resolve, and I think REP 105 is the right answer.

This is ultimately a question of what the frame_id should be.  This frame_id should NOT be 'odom_combined' just the same as every robot should have a 'base_link' and not 'my_bottom_link' or 'base_link_main_board'.  Any node that can calculate a form of odometry (hardware driver, robot_pose_ekf, VO, etc), typically support a 'publish_tf" parameter.  Only one of these nodes should publish the link from 'odom' to 'base_link', and the parent frame_id should not change based on who is publishing.

This is similar for 'map' being the global reference frame.  Ultimately it boils down to three standard frames that simplify many common robotics problems:
1) A globally accurate, but locally discontinuous frame ('map')
2) A globally inaccurate, but locally smooth frame ('odom')
3) A frame for the origin of the robot ('base_link')

However, the topic name with the associated node can change to be descriptive for the robot.  Typically we see 'odom', 'vo', 'visual_odom', 'odom_combined', and so on.  The platform maintainer can make the decisions here, but 'odom' is usually the topic name for the platform's odometry and 'odom_combined' is the output a fusion stage.

**Comment by bit-pirate** [comment]
Thanks Chad! What you explain makes sense to me. I'm fine with following this standard.

**Comment by stonier** [comment]
Ditto, closing. Thanks for the feedback guys.
