### ISSUE TITLE
REP specifies inaccurate camera_rgb_frame

### ISSUE THREAD

**Issue by bit-pirate** [turtlebot/turtlebot#60]
This issue has been around for a while now and I really would like to find a solution this time!

A while ago Younghoon found out, that there is a significant offset between the real camera_rgb_frame position and what we specify in the REP. This only concerns the position on the y-axis. 

This issue has been discussed on the [mailing list](https://groups.google.com/forum/?fromgroups=#!topic/ros-sig-turtlebot/qASjCIBTsK8), but ended with no result.

Here are two pictures showing it quite clearly:

![camera_rgb_frame_bug_turtlebot_hw](https://f.cloud.github.com/assets/1136833/225888/72403090-8609-11e2-8c0d-f8eea63e9cc3.png)
![camera_rgb_frame_bug_turtlebot_urdf](https://f.cloud.github.com/assets/1136833/225889/78003098-8609-11e2-970c-1d3f111e3cc6.png)

Younghoon's hypothesis is that the specified y value should be 12.5mm instead of 5mm. This error might got introduced because of mixing inches and millimeter, since 0.5 inches is roughly 12.5mm. With the later value, the rgb frame would be position better/correct.

After checking again we came to the conclusion that the rgf frame's y-position should be half of the distance between the rgb and depth frames, since that is the center of the Kinect. For Turtlebot 1 this distance was specified as 25mm, that's why 12.5mm would fit. However, newer measurements resulted in a distance of 27mm. So, we need to verify it again.

Hence, our suggestion is to update the camera_rgb_frame y-position in the [REP](http://www.ros.org/reps/rep-0119.html#compatibility-specification) to reflect the new placement based on the distance between rgb and depth frame.

Any objections?

**Comment by mmwise** [comment]
I am confused does the rep correctly represent TurtleBot 1? If it does we should not change the rep. The rep is meant to define what a compatible TurtleBot platform is with reference to TurtleBot 1.. We should not be changing the rep to reflect new hardware, the new hardware is supposed to follow the guidelines of the rep.
- Melonee

**Comment by bit-pirate** [comment]
What we are saying is that the REP is wrong in the way that Turtlebot 1 does not respect the REP.

The first picture shows, that the Kinect is centred with Kinect's centre being the middle between the RGB and depth lense/frame. In the second picture you can see that those frames are positioned wrong due to the error in the REP (both the RGB and depth frame are shifted to the right).

**Comment by stonier** [comment]
I had actually followed Younghoon's measurements four months ago given the lack of a logical reason why the above pictorial representation was wrong. I did forget to follow up on the REP though. And then you reverted back to the REP value in 8d9c04b276e73bf3b5ddb31a0de1753a161303f7 here Marcus - not sure why!

Anyway, I really think we should follow the logic here. I believe the REP is flat out wrong and unless there is a reason explaining the pictorial inconsistency above, we should change the REP.

**Comment by mmwise** [comment]
the coordinates came from our best measurements of the optical frames with
the kinect in the mounted position, if they are incorrect we should update
them, how are you guys determining the location of the optical frame do you
have an accurate CAD model with the optical frame locations?

**Comment by stonier** [comment]
Some more details. We have the CAD model from the original turtlebot description (kinect.dae) which also supports the assumptions and facts we're working from:
- Kinect rgb and depth frames lie on the axis passing through the centre of the circular discs.
- The frames are symetrically offset from the central axis of the kinect.
- The central axis of the kinect is mounted on plate 0 aligned with the central axis passing through the base link.
  - True for create and kobuki versions - see the mechanical drawings.

Conclusion:
- Consequently rgb and depth frames should be symmetrically offset from the central axis passing through the base link.

It is very apparent, that there is not just a small, but rather a large inconsistency from these base assumptions and what we can observe via either cad drawings, models or the human eye and rviz's urdf display.

So either our assumptions are erring, or the urdf settings are wrong. Our best explanation is that the REP parameter of y:-0.005m was perhaps accidentally recording the value in inches instead of mm (our best measurements read the offset at 12.5mm, which would be ~0.5 inches). Outside of that I haven't heard anything convincing that explains the very apparent discrepancy.

**Comment by stonier** [comment]
I don't think there is an officially accurate CAD model. At any rate, the errors we are talking about here are almost 1cm which are orders of magnitude higher than any errors you'd expect going from an estimated CAD model to an official one.

**Comment by bit-pirate** [comment]
My small additions:
I just have checked the distance between both lenses again and it's 25 mm (24.5 mm to be more precise). Hence, the offsets for the RGB and depth frame would each be 12.5 mm.

So, I will move forward and apply these measurements to the URDFs and if won't hear any objections I will take the freedom to change the REP the next days.

Sorry in advance, if I come across harsh, but I really want to get this thing out of our way and focus on more important (and interesting) things.

**Comment by mmwise** [comment]
that's fine with me I just wanted to make sure that I understood the
changes you wanted to make.

**Comment by stonier** [comment]
Closing, reopen if there's a problem with that pull request.
